### ISSUE TITLE
DLPack API Changes

### ISSUE THREAD

**Issue by adam-hartshorne** [rdyro/torch2jax#11]
I notice that there has just been quite a large change to dlpack pushed to the main branch of JAX.

Update from_dlpack to match array API 2023
https://github.com/google/jax/commits/2b1c3deee20600a43d512a3e69172e995a981d3e/jax/_src/dlpack.py

I don't know if this will be a breaking change for torch2jax?

**Comment by rdyro** [comment]
Thanks for keeping track of this! I'll be taking a look this week, I'll let you know

**Comment by rdyro** [comment]
I had some time to review this, thanks for pointing this out.

The tests still pass and I think this is mostly an API simplification change, so now it's simpler to use dlpack (as in less code), but the old API (that `torch2jax` still uses) is still fully supported and not deprecated.

Closing this now.
