### ISSUE TITLE
gcc version?

### ISSUE THREAD

**Issue by rkruegs123** [rdyro/torch2jax#14]
Hi -- thank you for this amazing package. I am making excellent use of it on some systems, but am having trouble with compilatoin on other systems -- which version of `gcc` do you use for testing?

**Comment by rdyro** [comment]
Hey, thanks!

I'm using the PyTorch [dynamic compilation utilities](https://pytorch.org/docs/stable/cpp_extension.html), which mostly use ninja under the hood. My own test system has gcc-12, but I'm not entirely sure which compiler PyTorch retrieves (I also have gcc-11).

For the official torch module performing the compilation wrapping, take a look at [torch.utils.cpp_extension](https://pytorch.org/docs/stable/cpp_extension.html)

For more details on how the extension is compiled, take a look at this logic: [torch2jax/compile.py](https://github.com/rdyro/torch2jax/blob/main/torch2jax/compile.py)

Let me know if this helps!

**Comment by rkruegs123** [comment]
Thank you for the quick response, and thank you again for your wonderful repository!
