### ISSUE TITLE
Handling situation of having two identically named packages

### ISSUE THREAD

**Issue by adam-hartshorne** [rdyro/torch2jax#9]
Given there are now two "torch2jax" packages, obviously, this makes it problematic if I want to install both and use them for slightly different purposes in the same virtual environment.

I am wondering what the way forward here is?

**Comment by rdyro** [comment]
I apologize for not having a solution yet, a stopgap solution is now mentioned in the README.md under `Related Work`. I provide a helper script to install this package under an aliased named, see:
- `install_package_aliased.py`

**Comment by rdyro** [comment]
The aliased PyPI installation is now available!

```bash
$ pip install wrap-torch2jax
$ # then
$ python3
$ >>> from wrap_torch2jax import torch2jax, torch2jax_with_vjp
```

@adam-hartshorne
